import {Car} from './Car'


const car = new Car()
car.TurnOnEngine()
console.log('IsTurnedOn ', car.IsTurnedOn())
car.TurnOffEngine()
console.log('IsTurnedOn ', car.IsTurnedOn())
car.TurnOnEngine()
// Проверка включения передачи
// console.log('GetGear ', car.GetGear())
// console.log('GetDirection ', car.GetDirection())
// console.log('GetSpeed ', car.GetSpeed())
// console.log('SetSpeed(-1)', car.SetSpeed(-1))
// console.log('SetSpeed(10)', car.SetSpeed(10))
// console.log('TurnOffEngine ', car.TurnOffEngine())
// console.log('SetSpeed(10)', car.SetSpeed(10))
// Проверка включения передачи


// console.log('SetGear(-1)', car.SetGear(-1))
// console.log('SetSpeed(10)', car.SetSpeed(10))
// console.log('GetSpeed', car.GetSpeed())
// console.log('GetDirection', car.GetDirection())
// console.log('SetSpeed(0)', car.SetSpeed(0))
// console.log('GetDirection', car.GetDirection())
// console.log('SetGear(-1)', car.SetGear(Gear.Rear))
// console.log('GetDirection', car.GetDirection())

console.log('SetGear(-1)', car.SetGear(-1))
console.log('SetSpeed(10)', car.SetSpeed(10))
// console.log('GetSpeed', car.GetSpeed())
console.log('GetDirection', car.GetDirection())
// console.log('SetGear(Gear.Neutral)', car.SetGear(Gear.Neutral))
// console.log('SetGear(1)', car.SetGear(Gear.First))
// console.log('GetGear', car.GetGear())
// console.log('GetDirection', car.GetDirection())
console.log('SetSpeed(0)', car.SetSpeed(0))
console.log('GetDirection', car.GetDirection())
console.log('SetGear(Gear.First)', car.SetGear(Gear.First))
console.log('SetSpeed(10)', car.SetSpeed(10))
console.log('GetSpeed', car.GetSpeed())
console.log('GetDirection', car.GetDirection())
// console.log('SetSpeed(50)', car.SetSpeed(50))
// console.log('GetSpeed', car.GetSpeed())
// console.log('SetSpeed(30)', car.SetSpeed(30))
// console.log('SetGear(Gear.Second)', car.SetGear(Gear.Second))
// console.log('SetGear(Gear.Third)', car.SetGear(Gear.Third))
// console.log('SetGear(Gear.Fourth)', car.SetGear(Gear.Fourth))
// console.log('GetGear', car.GetGear())
// console.log('GetDirection', car.GetDirection())
// console.log('GetSpeed()', car.GetSpeed())