import {Car} from './Car'


const kia = new Car()
kia.TurnOnEngine()
console.log('IsTurnedOn ', kia.IsTurnedOn())
kia.TurnOffEngine()
console.log('IsTurnedOn ', kia.IsTurnedOn())
kia.TurnOnEngine()
// Проверка включения передачи
// console.log('GetGear ', kia.GetGear())
// console.log('GetDirection ', kia.GetDirection())
// console.log('GetSpeed ', kia.GetSpeed())
// console.log('SetSpeed(-1)', kia.SetSpeed(-1))
// console.log('SetSpeed(10)', kia.SetSpeed(10))
// console.log('TurnOffEngine ', kia.TurnOffEngine())
// console.log('SetSpeed(10)', kia.SetSpeed(10))
// Проверка включения передачи


// console.log('SetGear(-1)', kia.SetGear(-1))
// console.log('SetSpeed(10)', kia.SetSpeed(10))
// console.log('GetSpeed', kia.GetSpeed())
// console.log('GetDirection', kia.GetDirection())
// console.log('SetSpeed(0)', kia.SetSpeed(0))
// console.log('GetDirection', kia.GetDirection())
// console.log('SetGear(-1)', kia.SetGear(Gear.Rear))
// console.log('GetDirection', kia.GetDirection())

console.log('SetGear(-1)', kia.SetGear(-1))
console.log('SetSpeed(10)', kia.SetSpeed(10))
// console.log('GetSpeed', kia.GetSpeed())
console.log('GetDirection', kia.GetDirection())
// console.log('SetGear(Gear.Neutral)', kia.SetGear(Gear.Neutral))
// console.log('SetGear(1)', kia.SetGear(Gear.First))
// console.log('GetGear', kia.GetGear())
// console.log('GetDirection', kia.GetDirection())
console.log('SetSpeed(0)', kia.SetSpeed(0))
console.log('GetDirection', kia.GetDirection())
console.log('SetGear(Gear.First)', kia.SetGear(Gear.First))
console.log('SetSpeed(10)', kia.SetSpeed(10))
console.log('GetSpeed', kia.GetSpeed())
console.log('GetDirection', kia.GetDirection())
// console.log('SetSpeed(50)', kia.SetSpeed(50))
// console.log('GetSpeed', kia.GetSpeed())
// console.log('SetSpeed(30)', kia.SetSpeed(30))
// console.log('SetGear(Gear.Second)', kia.SetGear(Gear.Second))
// console.log('SetGear(Gear.Third)', kia.SetGear(Gear.Third))
// console.log('SetGear(Gear.Fourth)', kia.SetGear(Gear.Fourth))
// console.log('GetGear', kia.GetGear())
// console.log('GetDirection', kia.GetDirection())
// console.log('GetSpeed()', kia.GetSpeed())